### ISSUE TITLE
Include info on how many keys can be bought or sold at once

### ISSUE THREAD

**Issue by carlosliam** [STNTrading/public-api#1]
Currently the API does not include any information on the maximum amount of keys that can be bought or sold at once, so I have to assume it is 10 even if it is actually lower than that, resulting in errors when attempting to buy or sell more keys than currently possible. Including this information would be helpful to reduce the amount of failed attempted trades.

**Comment by spyfly** [comment]
Thanks for your request, we have added a new endpoint which you can query before requesting a key trade: https://github.com/STNTrading/public-api/wiki/GetKeyStock
