### ISSUE TITLE
Able to buy items

### ISSUE THREAD

**Issue by de-pres** [STNTrading/public-api#3]
Just a api with post that will request to buy item by it name and amount of it, maybe get request to get item value, item amount in stock.

**Comment by spyfly** [comment]
Can you provide us with an example use-case for this feature?

If there is enough demand, we could look into adding such API endpoints.

**Comment by de-pres** [comment]
> Can you provide us with an example use-case for this feature?
> 
> If there is enough demand, we could look into adding such API endpoints.

` 
HTTP POST https://api.stntrading.eu/GetItem/v1?apikey={apikey}
{
    "Name":{item_name},
    "Amount":{amount_to_buy/"all"},
    "Quality":{item_quality}
}
HTTP POST https://api.stntrading.eu/SellItem/v1?apikey={apikey}
{
    "Name":{item_name},
    "Amount":{amount_to_buy/"all"},
    "Quality":{item_quality}
}


HTTP GET https://api.stntrading.eu/GetItemInfo/v1?apikey={apikey}?item={item_name}
RESPOND
[
{
"Amount":{item_in_stock},
"Buy_value":{"metal": {metal_cost}(int or float),"keys":{key_cost}(int)},
"Sell_value":{"metal": {metal_cost}(int or float),"keys":{key_cost}(int)},
"Quality":{item_quality}
},
]

OR

POST https://api.stntrading.eu/GetItemInfo/v1?apikey={Apikey}
{
    "Name":{item_name},
    "Quality":{item_quality}
}
RESPOND
{
    "Amount":{item_in_stock},
    "Buy_value":{"metal": {metal_cost}(int or float),"keys":{key_cost}(int)},
    "Sell_value":{"metal": {metal_cost}(int or float),"keys":{key_cost}(int)}
}
`

**Comment by carlosliam** [comment]
> Can you provide us with an example use-case for this feature?
> 
> 
> 
> If there is enough demand, we could look into adding such API endpoints.

I personally would be very interested in an API endpoint such as what is being suggested here.

An endpoint giving a list of items available to be bought or sold, as well as endpoints to get prices for each item and to create trades for them, is almost exactly what I'm looking for for a project I'm currently working on.

**Comment by spyfly** [comment]
@de-pres We would like to know the specific use-case and not how the API could be implemented.

@carlosliam What kind of project?

**Comment by carlosliam** [comment]
> @carlosliam What kind of project?

A trading bot that would automatically buy and sell items from backpack.tf classifieds bots as well as third-party websites to make profit through flipping, i.e. buy a Tour of Duty Ticket from (for example) STN for 30 ref and sell to a backpack.tf classified bot for 35 ref.

**Comment by de-pres** [comment]
> > @carlosliam What kind of project?
> 
> A trading bot that would automatically buy and sell items from backpack.tf classifieds bots as well as third-party websites to make profit through flipping, i.e. buy a Tour of Duty Ticket from (for example) STN for 30 ref and sell to a backpack.tf classified bot for 35 ref.

that's what I mean

**Comment by de-pres** [comment]
@spyfly so you will be working on this idea or no?

> @de-pres We would like to know the specific use-case and not how the API could be implemented.
> 
> @carlosliam What kind of project?

To automaticly sell items from on third-larty websites/users to gain some profit on intresting stn sale offers

**Comment by spyfly** [comment]
We may provide such API as a paid service in the future.

**Comment by snkxyz** [comment]
I would also be interested in such endpoints as I am also working on something that could make very great use of them.

**Comment by Osc44r** [comment]
People can not use POST requests lmao

**Comment by spyfly** [comment]
We are working on expanding our public API offerings (https://stntrading.eu/dev) and we are looking for possible beta testers, who are willing to test and evaluate our new API endpoints for trading, pricing and stock information.

If you are interested, feel free to submit an application to https://stntrading.eu/support with the subject "Developer API Beta" and tell us more about your special use-case.

**Comment by spyfly** [comment]
We have added a new endpoint, which allows executing any kind of queue request via API: https://github.com/STNTrading/public-api/wiki/RequestItemTrade
