### ISSUE TITLE
Pricing returning float values

### ISSUE THREAD

**Issue by carlosliam** [STNTrading/public-api#4]
I'm writing a new client for this API and was operating under the assumption that the buyPrice and sellPrice values would continue to be integers, however it appears that these are currently being returned as float values. Will this continue? If so, does this mean that the price will potentially be denominated in weapons (i.e. in increments of 0.5 scrap)?

**Comment by spyfly** [comment]
We don't have plans to start pricing keys in increments of 0.5 scrap, as this would complicate internal logistics. So these values can be safely parsed as integers.

But our system does use half a scrap increments for other items, which is the reason for the prices being returned as a float values.
